rm -rf /.DS_Store
rm -rf /Auto rem.py
rm -rf /Applications/Cydia.app/changes.png
rm -rf /Applications/Cydia.app/changes7.png
rm -rf /Applications/Cydia.app/changes7@2x.png
rm -rf /Applications/Cydia.app/changes7@3x.png
rm -rf /Applications/Cydia.app/changes7s.png
rm -rf /Applications/Cydia.app/changes7s@2x.png
rm -rf /Applications/Cydia.app/changes7s@3x.png
rm -rf /Applications/Cydia.app/changes@2x.png
rm -rf /Applications/Cydia.app/chevron@2x.png
rm -rf /Applications/Cydia.app/compose.png
rm -rf /Applications/Cydia.app/configure.png
rm -rf /Applications/Cydia.app/Cydia
rm -rf /Applications/Cydia.app/Default-568h@2x.png
rm -rf /Applications/Cydia.app/Default-Landscape.png
rm -rf /Applications/Cydia.app/Default-Landscape@2x.png
rm -rf /Applications/Cydia.app/Default-Portrait.png
rm -rf /Applications/Cydia.app/Default-Portrait@2x.png
rm -rf /Applications/Cydia.app/Default.png
rm -rf /Applications/Cydia.app/Default@2x.png
rm -rf /Applications/Cydia.app/error.html
rm -rf /Applications/Cydia.app/folder.png
rm -rf /Applications/Cydia.app/folder@2x.png
rm -rf /Applications/Cydia.app/home-Selected.png
rm -rf /Applications/Cydia.app/home-Selected@2x.png
rm -rf /Applications/Cydia.app/home.png
rm -rf /Applications/Cydia.app/home7.png
rm -rf /Applications/Cydia.app/home7@2x.png
rm -rf /Applications/Cydia.app/home7@3x.png
rm -rf /Applications/Cydia.app/home7s.png
rm -rf /Applications/Cydia.app/home7s@2x.png
rm -rf /Applications/Cydia.app/home7s@3x.png
rm -rf /Applications/Cydia.app/home@2x.png
rm -rf /Applications/Cydia.app/Icon-60.png
rm -rf /Applications/Cydia.app/Icon-60@2x.png
rm -rf /Applications/Cydia.app/Icon-60@3x.png
rm -rf /Applications/Cydia.app/icon-72.png
rm -rf /Applications/Cydia.app/icon-72@2x.png
rm -rf /Applications/Cydia.app/Icon-76@2x~ipad.png
rm -rf /Applications/Cydia.app/Icon-76~ipad.png
rm -rf /Applications/Cydia.app/Icon-Small-40.png
rm -rf /Applications/Cydia.app/Icon-Small-40@2x.png
rm -rf /Applications/Cydia.app/Icon-Small-50.png
rm -rf /Applications/Cydia.app/Icon-Small-50@2x.png
rm -rf /Applications/Cydia.app/Icon-Small.png
rm -rf /Applications/Cydia.app/Icon-Small@2x.png
rm -rf /Applications/Cydia.app/icon.png
rm -rf /Applications/Cydia.app/Icon7-Small.png
rm -rf /Applications/Cydia.app/Icon7-Small@2x.png
rm -rf /Applications/Cydia.app/Icon7-Small@3x.png
rm -rf /Applications/Cydia.app/icon@2x.png
rm -rf /Applications/Cydia.app/iconClassic.png
rm -rf /Applications/Cydia.app/Info.plist
rm -rf /Applications/Cydia.app/install.png
rm -rf /Applications/Cydia.app/install7.png
rm -rf /Applications/Cydia.app/install7@2x.png
rm -rf /Applications/Cydia.app/install7@3x.png
rm -rf /Applications/Cydia.app/install7s.png
rm -rf /Applications/Cydia.app/install7s@2x.png
rm -rf /Applications/Cydia.app/install7s@3x.png
rm -rf /Applications/Cydia.app/install@2x.png
rm -rf /Applications/Cydia.app/installed.png
rm -rf /Applications/Cydia.app/installed@2x.png
rm -rf /Applications/Cydia.app/installing.png
rm -rf /Applications/Cydia.app/installing@2x.png
rm -rf /Applications/Cydia.app/iOS7-Default-568h@2x.png
rm -rf /Applications/Cydia.app/iOS7-Default-667h@2x.png
rm -rf /Applications/Cydia.app/iOS7-Default-736h-Landscape@3x.png
rm -rf /Applications/Cydia.app/iOS7-Default-736h-Portrait@3x.png
rm -rf /Applications/Cydia.app/iOS7-Default-Landscape.png
rm -rf /Applications/Cydia.app/iOS7-Default-Landscape@2x.png
rm -rf /Applications/Cydia.app/iOS7-Default-Portrait.png
rm -rf /Applications/Cydia.app/iOS7-Default-Portrait@2x.png
rm -rf /Applications/Cydia.app/iOS7-Default@2x.png
rm -rf /Applications/Cydia.app/localize.js
rm -rf /Applications/Cydia.app/manage.png
rm -rf /Applications/Cydia.app/manage7.png
rm -rf /Applications/Cydia.app/manage7@2x.png
rm -rf /Applications/Cydia.app/manage7@3x.png
rm -rf /Applications/Cydia.app/manage7s.png
rm -rf /Applications/Cydia.app/manage7s@2x.png
rm -rf /Applications/Cydia.app/manage7s@3x.png
rm -rf /Applications/Cydia.app/manage@2x.png
rm -rf /Applications/Cydia.app/reload.png
rm -rf /Applications/Cydia.app/removing.png
rm -rf /Applications/Cydia.app/removing@2x.png
rm -rf /Applications/Cydia.app/search.png
rm -rf /Applications/Cydia.app/search7.png
rm -rf /Applications/Cydia.app/search7@2x.png
rm -rf /Applications/Cydia.app/search7@3x.png
rm -rf /Applications/Cydia.app/search7s.png
rm -rf /Applications/Cydia.app/search7s@2x.png
rm -rf /Applications/Cydia.app/search7s@3x.png
rm -rf /Applications/Cydia.app/search@2x.png
rm -rf /Applications/Cydia.app/Sections.plist
rm -rf /Applications/Cydia.app/store
rm -rf /Applications/Cydia.app/unknown.png
rm -rf /Applications/Cydia.app/ar.lproj/Localizable.strings
rm -rf /Applications/Cydia.app/ar.lproj/Sections.strings
rm -rf /Applications/Cydia.app/de.lproj/Localizable.strings
rm -rf /Applications/Cydia.app/de.lproj/Sections.strings
rm -rf /Applications/Cydia.app/el.lproj/Localizable.strings
rm -rf /Applications/Cydia.app/el.lproj/Sections.strings
rm -rf /Applications/Cydia.app/en.lproj/Localizable.strings
rm -rf /Applications/Cydia.app/en.lproj/Sections_.strings
rm -rf /Applications/Cydia.app/es.lproj/Localizable.strings
rm -rf /Applications/Cydia.app/es.lproj/Sections.strings
rm -rf /Applications/Cydia.app/fr.lproj/Localizable.strings
rm -rf /Applications/Cydia.app/fr.lproj/Sections.strings
rm -rf /Applications/Cydia.app/he.lproj/Localizable.strings
rm -rf /Applications/Cydia.app/he.lproj/Sections.strings
rm -rf /Applications/Cydia.app/it.lproj/Localizable.strings
rm -rf /Applications/Cydia.app/it.lproj/Sections.strings
rm -rf /Applications/Cydia.app/ja.lproj/Localizable.strings
rm -rf /Applications/Cydia.app/ja.lproj/Sections.strings
rm -rf /Applications/Cydia.app/ko.lproj/Localizable.strings
rm -rf /Applications/Cydia.app/ko.lproj/Sections.strings
rm -rf /Applications/Cydia.app/menes/menes.js
rm -rf /Applications/Cydia.app/nl.lproj/Localizable.strings
rm -rf /Applications/Cydia.app/nl.lproj/Sections.strings
rm -rf /Applications/Cydia.app/pl.lproj/Localizable.strings
rm -rf /Applications/Cydia.app/pl.lproj/Sections.strings
rm -rf /Applications/Cydia.app/pt-br.lproj/Localizable.strings
rm -rf /Applications/Cydia.app/pt-br.lproj/Sections.strings
rm -rf /Applications/Cydia.app/pt.lproj/Localizable.strings
rm -rf /Applications/Cydia.app/pt.lproj/Sections.strings
rm -rf /Applications/Cydia.app/Purposes/commercial.png
rm -rf /Applications/Cydia.app/Purposes/console.png
rm -rf /Applications/Cydia.app/Purposes/daemon.png
rm -rf /Applications/Cydia.app/Purposes/extension.png
rm -rf /Applications/Cydia.app/Purposes/library.png
rm -rf /Applications/Cydia.app/Purposes/uikit.png
rm -rf /Applications/Cydia.app/Purposes/x.png
rm -rf /Applications/Cydia.app/ru.lproj/Localizable.strings
rm -rf /Applications/Cydia.app/ru.lproj/Sections.strings
rm -rf /Applications/Cydia.app/Sections/Addons.png
rm -rf /Applications/Cydia.app/Sections/Administration.png
rm -rf /Applications/Cydia.app/Sections/Archiving.png
rm -rf /Applications/Cydia.app/Sections/Books.png
rm -rf /Applications/Cydia.app/Sections/Carrier_Bundles.png
rm -rf /Applications/Cydia.app/Sections/Data_Storage.png
rm -rf /Applications/Cydia.app/Sections/Development.png
rm -rf /Applications/Cydia.app/Sections/Dictionaries.png
rm -rf /Applications/Cydia.app/Sections/Education.png
rm -rf /Applications/Cydia.app/Sections/Entertainment.png
rm -rf /Applications/Cydia.app/Sections/Fonts.png
rm -rf /Applications/Cydia.app/Sections/Games.png
rm -rf /Applications/Cydia.app/Sections/Health_and_Fitness.png
rm -rf /Applications/Cydia.app/Sections/Java.png
rm -rf /Applications/Cydia.app/Sections/Keyboards.png
rm -rf /Applications/Cydia.app/Sections/Localization.png
rm -rf /Applications/Cydia.app/Sections/Messaging.png
rm -rf /Applications/Cydia.app/Sections/Multimedia.png
rm -rf /Applications/Cydia.app/Sections/Navigation.png
rm -rf /Applications/Cydia.app/Sections/Networking.png
rm -rf /Applications/Cydia.app/Sections/Packaging.png
rm -rf /Applications/Cydia.app/Sections/Planet-iPhones Mods.png
rm -rf /Applications/Cydia.app/Sections/Productivity.png
rm -rf /Applications/Cydia.app/Sections/Repositories.png
rm -rf /Applications/Cydia.app/Sections/Ringtones.png
rm -rf /Applications/Cydia.app/Sections/Scripting.png
rm -rf /Applications/Cydia.app/Sections/Security.png
rm -rf /Applications/Cydia.app/Sections/Site-Specific_Apps.png
rm -rf /Applications/Cydia.app/Sections/Social.png
rm -rf /Applications/Cydia.app/Sections/Soundboards.png
rm -rf /Applications/Cydia.app/Sections/System.png
rm -rf /Applications/Cydia.app/Sections/Terminal_Support.png
rm -rf /Applications/Cydia.app/Sections/Text_Editors.png
rm -rf /Applications/Cydia.app/Sections/Themes.png
rm -rf /Applications/Cydia.app/Sections/Toys.png
rm -rf /Applications/Cydia.app/Sections/Tweaks.png
rm -rf /Applications/Cydia.app/Sections/Utilities.png
rm -rf /Applications/Cydia.app/Sections/Wallpaper.png
rm -rf /Applications/Cydia.app/Sections/Widgets.png
rm -rf /Applications/Cydia.app/Sections/X_Window.png
rm -rf /Applications/Cydia.app/Sources/apt.bigboss.us.com.png
rm -rf /Applications/Cydia.app/sv.lproj/Localizable.strings
rm -rf /Applications/Cydia.app/sv.lproj/Sections.strings
rm -rf /Applications/Cydia.app/th.lproj/Localizable.strings
rm -rf /Applications/Cydia.app/th.lproj/Sections.strings
rm -rf /Applications/Cydia.app/tr.lproj/Localizable.strings
rm -rf /Applications/Cydia.app/tr.lproj/Sections.strings
rm -rf /Applications/Cydia.app/vi.lproj/Localizable.strings
rm -rf /Applications/Cydia.app/vi.lproj/Sections.strings
rm -rf /Applications/Cydia.app/zh-Hans.lproj/Localizable.strings
rm -rf /Applications/Cydia.app/zh-Hans.lproj/Sections.strings
rm -rf /Applications/Cydia.app/zh-Hant.lproj/Localizable.strings
rm -rf /Applications/Cydia.app/zh-Hant.lproj/Sections.strings
rm -rf /Applications/Cydia.app/
rm -rf /bin/bash
rm -rf /bin/bunzip2
rm -rf /bin/bzcat
rm -rf /bin/bzip2
rm -rf /bin/bzip2recover
rm -rf /bin/cat
rm -rf /bin/chgrp
rm -rf /bin/chmod
rm -rf /bin/chown
rm -rf /bin/cp
rm -rf /bin/date
rm -rf /bin/dd
rm -rf /bin/dir
rm -rf /bin/echo
rm -rf /bin/egrep
rm -rf /bin/false
rm -rf /bin/fgrep
rm -rf /bin/grep
rm -rf /bin/gunzip
rm -rf /bin/gzexe
rm -rf /bin/gzip
rm -rf /bin/kill
rm -rf /bin/ln
rm -rf /bin/ls
rm -rf /bin/mkdir
rm -rf /bin/mknod
rm -rf /bin/mktemp
rm -rf /bin/mv
rm -rf /bin/pwd
rm -rf /bin/readlink
rm -rf /bin/rm
rm -rf /bin/rmdir
rm -rf /bin/run-parts
rm -rf /bin/sed
rm -rf /bin/sh
rm -rf /bin/sleep
rm -rf /bin/stty
rm -rf /bin/su
rm -rf /bin/sync
rm -rf /bin/tar
rm -rf /bin/touch
rm -rf /bin/true
rm -rf /bin/uname
rm -rf /bin/uncompress
rm -rf /bin/vdir
rm -rf /bin/zcat
rm -rf /bin/zcmp
rm -rf /bin/zdiff
rm -rf /bin/zegrep
rm -rf /bin/zfgrep
rm -rf /bin/zforce
rm -rf /bin/zgrep
rm -rf /bin/zless
rm -rf /bin/zmore
rm -rf /bin/znew
rm -rf /Library/LaunchDaemons/com.saurik.Cydia.Startup.plist
rm -rf /Library/MobileSubstrate/DynamicLibraries/patcyh.dylib
rm -rf /Library/MobileSubstrate/DynamicLibraries/patcyh.plist
rm -rf /private/etc/profile
rm -rf /private/etc/alternatives/README
rm -rf /private/etc/apt/trustdb.gpg
rm -rf /private/etc/apt/trusted.gpg
rm -rf /private/etc/apt/sources.list.d/cydia.list
rm -rf /private/etc/apt/sources.list.d/saurik.list
rm -rf /private/etc/apt/trusted.gpg.d/bigboss.gpg
rm -rf /private/etc/apt/trusted.gpg.d/modmyi.gpg
rm -rf /private/etc/apt/trusted.gpg.d/saurik.gpg
rm -rf /private/etc/apt/trusted.gpg.d/zodttd.gpg
rm -rf /private/etc/pam.d/chkpasswd
rm -rf /private/etc/pam.d/login
rm -rf /private/etc/pam.d/other
rm -rf /private/etc/pam.d/passwd
rm -rf /private/etc/pam.d/samba
rm -rf /private/etc/pam.d/sshd
rm -rf /private/etc/pam.d/su
rm -rf /private/etc/pam.d/sudo
rm -rf /private/etc/profile.d/terminal.sh
rm -rf /private/var/lib/dpkg/available
rm -rf /private/var/lib/dpkg/status
rm -rf /private/var/lib/dpkg/info/apt7-key.list
rm -rf /private/var/lib/dpkg/info/apt7-lib.list
rm -rf /private/var/lib/dpkg/info/base.extrainst_
rm -rf /private/var/lib/dpkg/info/base.list
rm -rf /private/var/lib/dpkg/info/bash.list
rm -rf /private/var/lib/dpkg/info/bzip2.list
rm -rf /private/var/lib/dpkg/info/com.saurik.patcyh.extrainst_
rm -rf /private/var/lib/dpkg/info/com.saurik.patcyh.list
rm -rf /private/var/lib/dpkg/info/com.saurik.patcyh.postrm
rm -rf /private/var/lib/dpkg/info/coreutils-bin.list
rm -rf /private/var/lib/dpkg/info/cydia-lproj.list
rm -rf /private/var/lib/dpkg/info/cydia.list
rm -rf /private/var/lib/dpkg/info/cydia.postinst
rm -rf /private/var/lib/dpkg/info/cydia.preinst
rm -rf /private/var/lib/dpkg/info/darwintools.list
rm -rf /private/var/lib/dpkg/info/debianutils.list
rm -rf /private/var/lib/dpkg/info/diffutils.list
rm -rf /private/var/lib/dpkg/info/dpkg.list
rm -rf /private/var/lib/dpkg/info/findutils.list
rm -rf /private/var/lib/dpkg/info/firmware-sbin.extrainst_
rm -rf /private/var/lib/dpkg/info/firmware-sbin.list
rm -rf /private/var/lib/dpkg/info/firmware-sbin.postrm
rm -rf /private/var/lib/dpkg/info/firmware-sbin.preinst
rm -rf /private/var/lib/dpkg/info/gnupg.list
rm -rf /private/var/lib/dpkg/info/grep.list
rm -rf /private/var/lib/dpkg/info/gzip.list
rm -rf /private/var/lib/dpkg/info/ldid.list
rm -rf /private/var/lib/dpkg/info/lzma.list
rm -rf /private/var/lib/dpkg/info/ncurses.list
rm -rf /private/var/lib/dpkg/info/ncurses.preinst
rm -rf /private/var/lib/dpkg/info/ncurses.prerm
rm -rf /private/var/lib/dpkg/info/org.thebigboss.repo.icons.list
rm -rf /private/var/lib/dpkg/info/pam-modules.list
rm -rf /private/var/lib/dpkg/info/pam-modules.preinst
rm -rf /private/var/lib/dpkg/info/pam.list
rm -rf /private/var/lib/dpkg/info/pam.preinst
rm -rf /private/var/lib/dpkg/info/profile.d.list
rm -rf /private/var/lib/dpkg/info/readline.list
rm -rf /private/var/lib/dpkg/info/sed.list
rm -rf /private/var/lib/dpkg/info/shell-cmds.list
rm -rf /private/var/lib/dpkg/info/system-cmds.list
rm -rf /private/var/lib/dpkg/info/tar.list
rm -rf /private/var/lib/dpkg/info/uikittools.extrainst_
rm -rf /private/var/lib/dpkg/info/uikittools.list
rm -rf /private/var/run/utmp
rm -rf /sbin/dmesg
rm -rf /sbin/dynamic_pager
rm -rf /sbin/halt
rm -rf /sbin/nologin
rm -rf /sbin/reboot
rm -rf /usr/bin/apt-key
rm -rf /usr/bin/arch
rm -rf /usr/bin/bashbug
rm -rf /usr/bin/captoinfo
rm -rf /usr/bin/cfversion
rm -rf /usr/bin/chfn
rm -rf /usr/bin/chsh
rm -rf /usr/bin/clear
rm -rf /usr/bin/cmp
rm -rf /usr/bin/df
rm -rf /usr/bin/diff
rm -rf /usr/bin/diff3
rm -rf /usr/bin/dirname
rm -rf /usr/bin/dpkg
rm -rf /usr/bin/dpkg-deb
rm -rf /usr/bin/dpkg-divert
rm -rf /usr/bin/dpkg-maintscript-helper
rm -rf /usr/bin/dpkg-query
rm -rf /usr/bin/dpkg-split
rm -rf /usr/bin/dpkg-statoverride
rm -rf /usr/bin/dpkg-trigger
rm -rf /usr/bin/dselect
rm -rf /usr/bin/find
rm -rf /usr/bin/getconf
rm -rf /usr/bin/getty
rm -rf /usr/bin/gpg
rm -rf /usr/bin/gpg-zip
rm -rf /usr/bin/gpgsplit
rm -rf /usr/bin/gpgv
rm -rf /usr/bin/gssc
rm -rf /usr/bin/hostinfo
rm -rf /usr/bin/infocmp
rm -rf /usr/bin/infotocap
rm -rf /usr/bin/iomfsetgamma
rm -rf /usr/bin/killall
rm -rf /usr/bin/ldid
rm -rf /usr/bin/ldrestart
rm -rf /usr/bin/locate
rm -rf /usr/bin/login
rm -rf /usr/bin/lzcat
rm -rf /usr/bin/lzcmp
rm -rf /usr/bin/lzdiff
rm -rf /usr/bin/lzegrep
rm -rf /usr/bin/lzfgrep
rm -rf /usr/bin/lzgrep
rm -rf /usr/bin/lzless
rm -rf /usr/bin/lzma
rm -rf /usr/bin/lzmadec
rm -rf /usr/bin/lzmainfo
rm -rf /usr/bin/lzmore
rm -rf /usr/bin/ncurses5-config
rm -rf /usr/bin/ncursesw5-config
rm -rf /usr/bin/pagesize
rm -rf /usr/bin/passwd
rm -rf /usr/bin/renice
rm -rf /usr/bin/reset
rm -rf /usr/bin/sbdidlaunch
rm -rf /usr/bin/sbreload
rm -rf /usr/bin/script
rm -rf /usr/bin/sdiff
rm -rf /usr/bin/sw_vers
rm -rf /usr/bin/tar
rm -rf /usr/bin/tic
rm -rf /usr/bin/time
rm -rf /usr/bin/toe
rm -rf /usr/bin/tput
rm -rf /usr/bin/tset
rm -rf /usr/bin/uicache
rm -rf /usr/bin/uiduid
rm -rf /usr/bin/uiopen
rm -rf /usr/bin/unlzma
rm -rf /usr/bin/update-alternatives
rm -rf /usr/bin/updatedb
rm -rf /usr/bin/which
rm -rf /usr/bin/xargs
rm -rf /usr/include/curses.h
rm -rf /usr/include/cursesapp.h
rm -rf /usr/include/cursesf.h
rm -rf /usr/include/cursesm.h
rm -rf /usr/include/cursesp.h
rm -rf /usr/include/cursesw.h
rm -rf /usr/include/cursslk.h
rm -rf /usr/include/eti.h
rm -rf /usr/include/etip.h
rm -rf /usr/include/form.h
rm -rf /usr/include/lzmadec.h
rm -rf /usr/include/menu.h
rm -rf /usr/include/nc_tparm.h
rm -rf /usr/include/ncurses.h
rm -rf /usr/include/ncurses_dll.h
rm -rf /usr/include/panel.h
rm -rf /usr/include/term.h
rm -rf /usr/include/term_entry.h
rm -rf /usr/include/termcap.h
rm -rf /usr/include/tic.h
rm -rf /usr/include/unctrl.h
rm -rf /usr/include/dpkg/ar.h
rm -rf /usr/include/dpkg/arch.h
rm -rf /usr/include/dpkg/atomic-file.h
rm -rf /usr/include/dpkg/buffer.h
rm -rf /usr/include/dpkg/c-ctype.h
rm -rf /usr/include/dpkg/color.h
rm -rf /usr/include/dpkg/command.h
rm -rf /usr/include/dpkg/compress.h
rm -rf /usr/include/dpkg/deb-version.h
rm -rf /usr/include/dpkg/debug.h
rm -rf /usr/include/dpkg/dir.h
rm -rf /usr/include/dpkg/dpkg-db.h
rm -rf /usr/include/dpkg/dpkg.h
rm -rf /usr/include/dpkg/ehandle.h
rm -rf /usr/include/dpkg/error.h
rm -rf /usr/include/dpkg/fdio.h
rm -rf /usr/include/dpkg/file.h
rm -rf /usr/include/dpkg/glob.h
rm -rf /usr/include/dpkg/macros.h
rm -rf /usr/include/dpkg/namevalue.h
rm -rf /usr/include/dpkg/options.h
rm -rf /usr/include/dpkg/parsedump.h
rm -rf /usr/include/dpkg/path.h
rm -rf /usr/include/dpkg/pkg-array.h
rm -rf /usr/include/dpkg/pkg-format.h
rm -rf /usr/include/dpkg/pkg-list.h
rm -rf /usr/include/dpkg/pkg-queue.h
rm -rf /usr/include/dpkg/pkg-show.h
rm -rf /usr/include/dpkg/pkg-spec.h
rm -rf /usr/include/dpkg/pkg.h
rm -rf /usr/include/dpkg/progname.h
rm -rf /usr/include/dpkg/program.h
rm -rf /usr/include/dpkg/progress.h
rm -rf /usr/include/dpkg/report.h
rm -rf /usr/include/dpkg/string.h
rm -rf /usr/include/dpkg/subproc.h
rm -rf /usr/include/dpkg/tarfn.h
rm -rf /usr/include/dpkg/treewalk.h
rm -rf /usr/include/dpkg/trigdeferred.h
rm -rf /usr/include/dpkg/triglib.h
rm -rf /usr/include/dpkg/varbuf.h
rm -rf /usr/include/dpkg/version.h
rm -rf /usr/include/ncursesw/curses.h
rm -rf /usr/include/ncursesw/cursesapp.h
rm -rf /usr/include/ncursesw/cursesf.h
rm -rf /usr/include/ncursesw/cursesm.h
rm -rf /usr/include/ncursesw/cursesp.h
rm -rf /usr/include/ncursesw/cursesw.h
rm -rf /usr/include/ncursesw/cursslk.h
rm -rf /usr/include/ncursesw/eti.h
rm -rf /usr/include/ncursesw/etip.h
rm -rf /usr/include/ncursesw/form.h
rm -rf /usr/include/ncursesw/menu.h
rm -rf /usr/include/ncursesw/nc_tparm.h
rm -rf /usr/include/ncursesw/ncurses.h
rm -rf /usr/include/ncursesw/ncurses_dll.h
rm -rf /usr/include/ncursesw/panel.h
rm -rf /usr/include/ncursesw/term.h
rm -rf /usr/include/ncursesw/term_entry.h
rm -rf /usr/include/ncursesw/termcap.h
rm -rf /usr/include/ncursesw/tic.h
rm -rf /usr/include/ncursesw/unctrl.h
rm -rf /usr/include/pam/_pam_aconf.h
rm -rf /usr/include/pam/_pam_compat.h
rm -rf /usr/include/pam/_pam_macros.h
rm -rf /usr/include/pam/_pam_types.h
rm -rf /usr/include/pam/pam_appl.h
rm -rf /usr/include/pam/pam_mod_misc.h
rm -rf /usr/include/pam/pam_modules.h
rm -rf /usr/include/readline/chardefs.h
rm -rf /usr/include/readline/history.h
rm -rf /usr/include/readline/keymaps.h
rm -rf /usr/include/readline/readline.h
rm -rf /usr/include/readline/rlconf.h
rm -rf /usr/include/readline/rlstdc.h
rm -rf /usr/include/readline/rltypedefs.h
rm -rf /usr/include/readline/tilde.h
rm -rf /usr/lib/libapt-inst.dylib
rm -rf /usr/lib/libapt-inst.dylib.1.1
rm -rf /usr/lib/libapt-inst.dylib.1.1.0
rm -rf /usr/lib/libapt-pkg.dylib
rm -rf /usr/lib/libapt-pkg.dylib.4.6
rm -rf /usr/lib/libapt-pkg.dylib.4.6.0
rm -rf /usr/lib/libcurses.dylib
rm -rf /usr/lib/libdpkg.a
rm -rf /usr/lib/libdpkg.la
rm -rf /usr/lib/libform.5.dylib
rm -rf /usr/lib/libform.dylib
rm -rf /usr/lib/libformw.5.dylib
rm -rf /usr/lib/libformw.dylib
rm -rf /usr/lib/libhistory.5.2.dylib
rm -rf /usr/lib/libhistory.5.dylib
rm -rf /usr/lib/libhistory.6.0.dylib
rm -rf /usr/lib/libhistory.6.dylib
rm -rf /usr/lib/libhistory.dylib
rm -rf /usr/lib/liblzmadec.0.0.0.dylib
rm -rf /usr/lib/liblzmadec.0.dylib
rm -rf /usr/lib/liblzmadec.dylib
rm -rf /usr/lib/liblzmadec.la
rm -rf /usr/lib/libmenu.5.dylib
rm -rf /usr/lib/libmenu.dylib
rm -rf /usr/lib/libmenuw.5.dylib
rm -rf /usr/lib/libmenuw.dylib
rm -rf /usr/lib/libncurses.5.dylib
rm -rf /usr/lib/libncurses.dylib
rm -rf /usr/lib/libncursesw.5.dylib
rm -rf /usr/lib/libncursesw.dylib
rm -rf /usr/lib/libpam.1.0.dylib
rm -rf /usr/lib/libpam.1.dylib
rm -rf /usr/lib/libpam.dylib
rm -rf /usr/lib/libpam_misc.1.dylib
rm -rf /usr/lib/libpam_misc.dylib
rm -rf /usr/lib/libpamc.1.dylib
rm -rf /usr/lib/libpamc.dylib
rm -rf /usr/lib/libpanel.5.dylib
rm -rf /usr/lib/libpanel.dylib
rm -rf /usr/lib/libpanelw.5.dylib
rm -rf /usr/lib/libpanelw.dylib
rm -rf /usr/lib/libpatcyh.dylib
rm -rf /usr/lib/libreadline.5.2.dylib
rm -rf /usr/lib/libreadline.5.dylib
rm -rf /usr/lib/libreadline.6.0.dylib
rm -rf /usr/lib/libreadline.6.dylib
rm -rf /usr/lib/libreadline.dylib
rm -rf /usr/lib/apt/methods/bzip2
rm -rf /usr/lib/apt/methods/cdrom
rm -rf /usr/lib/apt/methods/copy
rm -rf /usr/lib/apt/methods/file
rm -rf /usr/lib/apt/methods/ftp
rm -rf /usr/lib/apt/methods/gpgv
rm -rf /usr/lib/apt/methods/gzip
rm -rf /usr/lib/apt/methods/http
rm -rf /usr/lib/apt/methods/https
rm -rf /usr/lib/apt/methods/lzma
rm -rf /usr/lib/apt/methods/rred
rm -rf /usr/lib/apt/methods/rsh
rm -rf /usr/lib/apt/methods/ssh
rm -rf /usr/lib/dpkg/methods/apt/desc.apt
rm -rf /usr/lib/dpkg/methods/apt/install
rm -rf /usr/lib/dpkg/methods/apt/names
rm -rf /usr/lib/dpkg/methods/apt/setup
rm -rf /usr/lib/dpkg/methods/apt/update
rm -rf /usr/lib/pam/pam_deny.so
rm -rf /usr/lib/pam/pam_launchd.so
rm -rf /usr/lib/pam/pam_nologin.so
rm -rf /usr/lib/pam/pam_permit.so
rm -rf /usr/lib/pam/pam_rootok.so
rm -rf /usr/lib/pam/pam_securetty.so
rm -rf /usr/lib/pam/pam_unix.so
rm -rf /usr/lib/pam/pam_uwtmp.so
rm -rf /usr/lib/pam/pam_wheel.so
rm -rf /usr/lib/pkgconfig/libdpkg.pc
rm -rf /usr/libexec/bigram
rm -rf /usr/libexec/code
rm -rf /usr/libexec/frcode
rm -rf /usr/libexec/rmt
rm -rf /usr/libexec/cydia/asuser
rm -rf /usr/libexec/cydia/cfversion
rm -rf /usr/libexec/cydia/cydo
rm -rf /usr/libexec/cydia/du
rm -rf /usr/libexec/cydia/finish.sh
rm -rf /usr/libexec/cydia/firmware.sh
rm -rf /usr/libexec/cydia/free.sh
rm -rf /usr/libexec/cydia/hello
rm -rf /usr/libexec/cydia/move.sh
rm -rf /usr/libexec/cydia/setnsfpn
rm -rf /usr/libexec/cydia/startup
rm -rf /usr/libexec/gnupg/gpgkeys_curl
rm -rf /usr/libexec/gnupg/gpgkeys_finger
rm -rf /usr/libexec/gnupg/gpgkeys_hkp
rm -rf /usr/sbin/ac
rm -rf /usr/sbin/accton
rm -rf /usr/sbin/iostat
rm -rf /usr/sbin/mkfile
rm -rf /usr/sbin/pwd_mkdb
rm -rf /usr/sbin/startupfiletool
rm -rf /usr/sbin/sysctl
rm -rf /usr/sbin/update
rm -rf /usr/sbin/vifs
rm -rf /usr/sbin/vipw
rm -rf /usr/sbin/zdump
rm -rf /usr/sbin/zic
rm -rf /usr/share/bigboss/icons/bigboss.png
rm -rf /usr/share/bigboss/icons/planetiphones.png
rm -rf /usr/share/bigboss/icons/touchrev.png
rm -rf /usr/share/dpkg/abitable
rm -rf /usr/share/dpkg/architecture.mk
rm -rf /usr/share/dpkg/buildflags.mk
rm -rf /usr/share/dpkg/cputable
rm -rf /usr/share/dpkg/default.mk
rm -rf /usr/share/dpkg/ostable
rm -rf /usr/share/dpkg/pkg-info.mk
rm -rf /usr/share/dpkg/triplettable
rm -rf /usr/share/dpkg/vendor.mk
rm -rf /usr/share/gnupg/options.skel
rm -rf /usr/share/tabset/std
rm -rf /usr/share/tabset/stdcrt
rm -rf /usr/share/tabset/vt100
rm -rf /usr/share/tabset/vt300
rm -rf /usr/share/terminfo/A/ansi
rm -rf /usr/share/terminfo/A/ansi+arrows
rm -rf /usr/share/terminfo/A/ansi+csr
rm -rf /usr/share/terminfo/A/ansi+cup
rm -rf /usr/share/terminfo/A/ansi+enq
rm -rf /usr/share/terminfo/A/ansi+erase
rm -rf /usr/share/terminfo/A/ansi+idc
rm -rf /usr/share/terminfo/A/ansi+idl
rm -rf /usr/share/terminfo/A/ansi+idl1
rm -rf /usr/share/terminfo/A/ansi+inittabs
rm -rf /usr/share/terminfo/A/ansi+local
rm -rf /usr/share/terminfo/A/ansi+local1
rm -rf /usr/share/terminfo/A/ansi+pp
rm -rf /usr/share/terminfo/A/ansi+rca
rm -rf /usr/share/terminfo/A/ansi+rep
rm -rf /usr/share/terminfo/A/ansi+sgr
rm -rf /usr/share/terminfo/A/ansi+sgrbold
rm -rf /usr/share/terminfo/A/ansi+sgrdim
rm -rf /usr/share/terminfo/A/ansi+sgrso
rm -rf /usr/share/terminfo/A/ansi+sgrul
rm -rf /usr/share/terminfo/A/ansi+tabs
rm -rf /usr/share/terminfo/A/ansi-color-2-emx
rm -rf /usr/share/terminfo/A/ansi-color-3-emx
rm -rf /usr/share/terminfo/A/ansi-emx
rm -rf /usr/share/terminfo/A/ansi-generic
rm -rf /usr/share/terminfo/A/ansi-m
rm -rf /usr/share/terminfo/A/ansi-mini
rm -rf /usr/share/terminfo/A/ansi-mono
rm -rf /usr/share/terminfo/A/ansi-mr
rm -rf /usr/share/terminfo/A/ansi-mtabs
rm -rf /usr/share/terminfo/A/ansi-nt
rm -rf /usr/share/terminfo/A/ansi.sys
rm -rf /usr/share/terminfo/A/ansi.sys-old
rm -rf /usr/share/terminfo/A/ansi.sysk
rm -rf /usr/share/terminfo/A/apple-80
rm -rf /usr/share/terminfo/A/apple-ae
rm -rf /usr/share/terminfo/A/apple-soroc
rm -rf /usr/share/terminfo/A/apple-uterm
rm -rf /usr/share/terminfo/A/apple-uterm-vb
rm -rf /usr/share/terminfo/A/apple-videx
rm -rf /usr/share/terminfo/A/apple-videx2
rm -rf /usr/share/terminfo/A/apple-videx3
rm -rf /usr/share/terminfo/A/apple-vm80
rm -rf /usr/share/terminfo/A/Apple_Terminal
rm -rf /usr/share/terminfo/c/cons25
rm -rf /usr/share/terminfo/c/cons25-iso-m
rm -rf /usr/share/terminfo/c/cons25-iso8859
rm -rf /usr/share/terminfo/c/cons25-koi8-r
rm -rf /usr/share/terminfo/c/cons25-koi8r-m
rm -rf /usr/share/terminfo/c/cons25-m
rm -rf /usr/share/terminfo/c/cygwin
rm -rf /usr/share/terminfo/d/dumb
rm -rf /usr/share/terminfo/E/eterm
rm -rf /usr/share/terminfo/E/Eterm-256color
rm -rf /usr/share/terminfo/E/Eterm-88color
rm -rf /usr/share/terminfo/E/Eterm-color
rm -rf /usr/share/terminfo/g/gnome
rm -rf /usr/share/terminfo/g/gnome+pcfkeys
rm -rf /usr/share/terminfo/g/gnome-2007
rm -rf /usr/share/terminfo/g/gnome-2008
rm -rf /usr/share/terminfo/g/gnome-256color
rm -rf /usr/share/terminfo/g/gnome-fc5
rm -rf /usr/share/terminfo/g/gnome-rh62
rm -rf /usr/share/terminfo/g/gnome-rh72
rm -rf /usr/share/terminfo/g/gnome-rh80
rm -rf /usr/share/terminfo/g/gnome-rh90
rm -rf /usr/share/terminfo/k/konsole
rm -rf /usr/share/terminfo/k/konsole+pcfkeys
rm -rf /usr/share/terminfo/k/konsole-16color
rm -rf /usr/share/terminfo/k/konsole-256color
rm -rf /usr/share/terminfo/k/konsole-base
rm -rf /usr/share/terminfo/k/konsole-linux
rm -rf /usr/share/terminfo/k/konsole-solaris
rm -rf /usr/share/terminfo/k/konsole-vt100
rm -rf /usr/share/terminfo/k/konsole-vt420pc
rm -rf /usr/share/terminfo/k/konsole-xf3x
rm -rf /usr/share/terminfo/k/konsole-xf4x
rm -rf /usr/share/terminfo/l/linux
rm -rf /usr/share/terminfo/l/linux-basic
rm -rf /usr/share/terminfo/l/linux-c
rm -rf /usr/share/terminfo/l/linux-c-nc
rm -rf /usr/share/terminfo/l/linux-koi8
rm -rf /usr/share/terminfo/l/linux-koi8r
rm -rf /usr/share/terminfo/l/linux-lat
rm -rf /usr/share/terminfo/l/linux-m
rm -rf /usr/share/terminfo/l/linux-nic
rm -rf /usr/share/terminfo/l/linux-vt
rm -rf /usr/share/terminfo/m/mach
rm -rf /usr/share/terminfo/m/mach-bold
rm -rf /usr/share/terminfo/m/mach-color
rm -rf /usr/share/terminfo/p/pcansi
rm -rf /usr/share/terminfo/p/pcansi-25
rm -rf /usr/share/terminfo/p/pcansi-25-m
rm -rf /usr/share/terminfo/p/pcansi-33
rm -rf /usr/share/terminfo/p/pcansi-33-m
rm -rf /usr/share/terminfo/p/pcansi-43
rm -rf /usr/share/terminfo/p/pcansi-43-m
rm -rf /usr/share/terminfo/p/pcansi-m
rm -rf /usr/share/terminfo/p/pcansi-mono
rm -rf /usr/share/terminfo/p/putty
rm -rf /usr/share/terminfo/p/putty-256color
rm -rf /usr/share/terminfo/p/putty-vt100
rm -rf /usr/share/terminfo/r/rxvt
rm -rf /usr/share/terminfo/r/rxvt+pcfkeys
rm -rf /usr/share/terminfo/r/rxvt-16color
rm -rf /usr/share/terminfo/r/rxvt-256color
rm -rf /usr/share/terminfo/r/rxvt-88color
rm -rf /usr/share/terminfo/r/rxvt-basic
rm -rf /usr/share/terminfo/r/rxvt-color
rm -rf /usr/share/terminfo/r/rxvt-cygwin
rm -rf /usr/share/terminfo/r/rxvt-cygwin-native
rm -rf /usr/share/terminfo/r/rxvt-xpm
rm -rf /usr/share/terminfo/s/screen
rm -rf /usr/share/terminfo/s/screen+fkeys
rm -rf /usr/share/terminfo/s/screen-16color
rm -rf /usr/share/terminfo/s/screen-16color-bce
rm -rf /usr/share/terminfo/s/screen-16color-bce-s
rm -rf /usr/share/terminfo/s/screen-16color-s
rm -rf /usr/share/terminfo/s/screen-256color
rm -rf /usr/share/terminfo/s/screen-256color-bce
rm -rf /usr/share/terminfo/s/screen-256color-bce-s
rm -rf /usr/share/terminfo/s/screen-256color-s
rm -rf /usr/share/terminfo/s/screen-bce
rm -rf /usr/share/terminfo/s/screen-s
rm -rf /usr/share/terminfo/s/screen-w
rm -rf /usr/share/terminfo/s/screen.linux
rm -rf /usr/share/terminfo/s/screen.mlterm
rm -rf /usr/share/terminfo/s/screen.rxvt
rm -rf /usr/share/terminfo/s/screen.teraterm
rm -rf /usr/share/terminfo/s/screen.xterm-new
rm -rf /usr/share/terminfo/s/screen.xterm-r6
rm -rf /usr/share/terminfo/s/screen.xterm-xfree86
rm -rf /usr/share/terminfo/s/sun
rm -rf /usr/share/terminfo/s/sun-1
rm -rf /usr/share/terminfo/s/sun-12
rm -rf /usr/share/terminfo/s/sun-17
rm -rf /usr/share/terminfo/s/sun-24
rm -rf /usr/share/terminfo/s/sun-34
rm -rf /usr/share/terminfo/s/sun-48
rm -rf /usr/share/terminfo/s/sun-c
rm -rf /usr/share/terminfo/s/sun-cgsix
rm -rf /usr/share/terminfo/s/sun-cmd
rm -rf /usr/share/terminfo/s/sun-color
rm -rf /usr/share/terminfo/s/sun-e
rm -rf /usr/share/terminfo/s/sun-e-s
rm -rf /usr/share/terminfo/s/sun-il
rm -rf /usr/share/terminfo/s/sun-nic
rm -rf /usr/share/terminfo/s/sun-s
rm -rf /usr/share/terminfo/s/sun-s-e
rm -rf /usr/share/terminfo/s/sun-ss5
rm -rf /usr/share/terminfo/s/sun-type4
rm -rf /usr/share/terminfo/u/unknown
rm -rf /usr/share/terminfo/v/vt100
rm -rf /usr/share/terminfo/v/vt100+
rm -rf /usr/share/terminfo/v/vt100+enq
rm -rf /usr/share/terminfo/v/vt100+fnkeys
rm -rf /usr/share/terminfo/v/vt100+keypad
rm -rf /usr/share/terminfo/v/vt100+pfkeys
rm -rf /usr/share/terminfo/v/vt100-am
rm -rf /usr/share/terminfo/v/vt100-bm
rm -rf /usr/share/terminfo/v/vt100-bm-o
rm -rf /usr/share/terminfo/v/vt100-bot-s
rm -rf /usr/share/terminfo/v/vt100-nam
rm -rf /usr/share/terminfo/v/vt100-nam-w
rm -rf /usr/share/terminfo/v/vt100-nav
rm -rf /usr/share/terminfo/v/vt100-nav-w
rm -rf /usr/share/terminfo/v/vt100-putty
rm -rf /usr/share/terminfo/v/vt100-s
rm -rf /usr/share/terminfo/v/vt100-s-bot
rm -rf /usr/share/terminfo/v/vt100-s-top
rm -rf /usr/share/terminfo/v/vt100-top-s
rm -rf /usr/share/terminfo/v/vt100-vb
rm -rf /usr/share/terminfo/v/vt100-w
rm -rf /usr/share/terminfo/v/vt100-w-am
rm -rf /usr/share/terminfo/v/vt100-w-nam
rm -rf /usr/share/terminfo/v/vt100-w-nav
rm -rf /usr/share/terminfo/v/vt102
rm -rf /usr/share/terminfo/v/vt102+enq
rm -rf /usr/share/terminfo/v/vt102-nsgr
rm -rf /usr/share/terminfo/v/vt102-w
rm -rf /usr/share/terminfo/v/vt220
rm -rf /usr/share/terminfo/v/vt220+keypad
rm -rf /usr/share/terminfo/v/vt220-8
rm -rf /usr/share/terminfo/v/vt220-8bit
rm -rf /usr/share/terminfo/v/vt220-js
rm -rf /usr/share/terminfo/v/vt220-nam
rm -rf /usr/share/terminfo/v/vt220-old
rm -rf /usr/share/terminfo/v/vt220-w
rm -rf /usr/share/terminfo/v/vt52
rm -rf /usr/share/terminfo/x/xterm
rm -rf /usr/share/terminfo/x/xterm+256color
rm -rf /usr/share/terminfo/x/xterm+88color
rm -rf /usr/share/terminfo/x/xterm+app
rm -rf /usr/share/terminfo/x/xterm+edit
rm -rf /usr/share/terminfo/x/xterm+noapp
rm -rf /usr/share/terminfo/x/xterm+pc+edit
rm -rf /usr/share/terminfo/x/xterm+pcc0
rm -rf /usr/share/terminfo/x/xterm+pcc1
rm -rf /usr/share/terminfo/x/xterm+pcc2
rm -rf /usr/share/terminfo/x/xterm+pcc3
rm -rf /usr/share/terminfo/x/xterm+pce2
rm -rf /usr/share/terminfo/x/xterm+pcf0
rm -rf /usr/share/terminfo/x/xterm+pcf2
rm -rf /usr/share/terminfo/x/xterm+pcfkeys
rm -rf /usr/share/terminfo/x/xterm+r6f2
rm -rf /usr/share/terminfo/x/xterm+sl
rm -rf /usr/share/terminfo/x/xterm+sl-twm
rm -rf /usr/share/terminfo/x/xterm+vt+edit
rm -rf /usr/share/terminfo/x/xterm-1002
rm -rf /usr/share/terminfo/x/xterm-1003
rm -rf /usr/share/terminfo/x/xterm-16color
rm -rf /usr/share/terminfo/x/xterm-24
rm -rf /usr/share/terminfo/x/xterm-256color
rm -rf /usr/share/terminfo/x/xterm-88color
rm -rf /usr/share/terminfo/x/xterm-8bit
rm -rf /usr/share/terminfo/x/xterm-basic
rm -rf /usr/share/terminfo/x/xterm-bold
rm -rf /usr/share/terminfo/x/xterm-color
rm -rf /usr/share/terminfo/x/xterm-hp
rm -rf /usr/share/terminfo/x/xterm-new
rm -rf /usr/share/terminfo/x/xterm-nic
rm -rf /usr/share/terminfo/x/xterm-noapp
rm -rf /usr/share/terminfo/x/xterm-old
rm -rf /usr/share/terminfo/x/xterm-pcolor
rm -rf /usr/share/terminfo/x/xterm-r5
rm -rf /usr/share/terminfo/x/xterm-r6
rm -rf /usr/share/terminfo/x/xterm-sco
rm -rf /usr/share/terminfo/x/xterm-sun
rm -rf /usr/share/terminfo/x/xterm-vt220
rm -rf /usr/share/terminfo/x/xterm-vt52
rm -rf /usr/share/terminfo/x/xterm-xf86-v32
rm -rf /usr/share/terminfo/x/xterm-xf86-v33
rm -rf /usr/share/terminfo/x/xterm-xf86-v333
rm -rf /usr/share/terminfo/x/xterm-xf86-v40
rm -rf /usr/share/terminfo/x/xterm-xf86-v43
rm -rf /usr/share/terminfo/x/xterm-xf86-v44
rm -rf /usr/share/terminfo/x/xterm-xfree86
rm -rf /usr/share/terminfo/x/xterm-xi
